### ISSUE TITLE
Consider replacing NamedTuple with dataclass

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#11]
### Description

Model parameters and state variables are currently defined with NamedTuple. It may be worth switching to dataclasses, as it allows more flexibility (it's mutable). 

This will impact existing raven code, so it might be best to plan that switch in advance and not roll it with all the other changes.

**Comment by cjauvin** [comment]
I have experimented with having my `ravenpy.models.commands` data containers be dataclasses instead of `NamedTuple`, and the problem is that they can't have default mutable fields, like an empty list for instance. That is a problem for certain types of Raven commands like `GridWeightsCommand` for instance, which has a `List[Tuple[int, int, float]]` member.

**Comment by huard** [comment]
Closed by #30
