### ISSUE TITLE
Package the RAVEN and OSTRICH binaries

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenPy#63]
The way that we install the RAVEN (http://raven.uwaterloo.ca/Downloads.html) and OSTRICH (https://www.civil.uwaterloo.ca/envmodelling/Ostrich.html) binaries assume that a lot of system libraries are available (things like GCC/CLANG + others). Once we've installed the binaries, the way we manage upgrading to a new version is to manually delete the existing files with a `make` command and to re-download the new files.

Given that we spend a lot of effort ensuring that packages bundle the proper requirements and dependency versions, why don't we try to promote the same practices being adopted for RAVEN and OSTRICH? Presently, we are trying to find workarounds to make `pip` manage the installation of these binary files (e.g. https://github.com/CSHS-CWRA/RavenPy/pull/62) but this is really a stretch of what `pip` is meant to be used for.

I would like to know whether we can speak with the maintainers of the RAVEN and OSTRICH code to see if we can aid with the packaging of these binaries (at least into `conda-forge` binary installable from an `environment.yml` or, ideally, into `dpkg` file installable from `apt`). I think this would be of great value to all users.

**Comment by cjauvin** [comment]
I understand that what I have proposed in https://github.com/CSHS-CWRA/RavenPy/pull/62 is far from ideal and that we should have a better solution someday.

However in the interim, this solution is much better than what we currently have because at least it takes care of the only use case we have right now: people who will work on RavenPy (i.e. they need both to install in `--editable` AND a way to get the binaries that is not exagerately :exploding_head:).

I already spent a lot of time dealing with these issues for Julie and Mohammad in the past couple of days, who have exactly those requirements.

**Comment by huard** [comment]
Can be closed ?

**Comment by Zeitsperre** [comment]
I suppose so. Everything for conda is still working off my personal branch, but the installation process tor pip is Good Enough™. We can open another issue for getting the Ostrich and Raven release/tag process figured out for GitHub in the maintenance phase.

**Comment by cjauvin** [comment]
I don't understand what is the issue with the personal branch.. the conda solution is MUCH better than the pip shenanigans no?

**Comment by cjauvin** [comment]
I think this is mostly solved (although I still think we should get rid of the half-baked pip-only logic that is still in `setup.py`).
